export const COMBAT_AFFORDANCE_TYPES = [
  "combat.move",
  "combat.stand",
  "combat.drop_prone",
  "combat.jump",
  "combat.climb",
  "combat.swim",
  "combat.crawl",
  "combat.fly",
  "combat.burrow",
  "combat.mount",
  "combat.dismount",
  "combat.dash",
  "combat.disengage",
  "combat.dodge",
  "combat.help",
  "combat.hide",
  "combat.search",
  "combat.study",
  "combat.influence",
  "combat.ready",
  "combat.utilize",
  "combat.interact",
  "combat.attack",
  "combat.unarmed",
  "combat.grapple",
  "combat.shove",
  "combat.escape_grapple",
  "combat.release_grapple",
  "combat.cast_spell",
  "combat.use_ability",
  "combat.use_item",
  "combat.equip",
  "combat.unequip",
  "combat.speak",
  "combat.whisper",
  "combat.ask_human",
  "combat.wait",
  "combat.decline",
  "combat.end_turn",
  "combat.improvise"
] as const;

export type CombatAffordanceType = (typeof COMBAT_AFFORDANCE_TYPES)[number];

export const FIRST_SLICE_COMBAT_TYPES: readonly CombatAffordanceType[] = [
  "combat.move",
  "combat.attack",
  "combat.cast_spell",
  "combat.use_ability",
  "combat.speak",
  "combat.wait",
  "combat.end_turn"
];
