export const WORLD_AFFORDANCE_TYPES = [
  "world.move",
  "world.follow",
  "world.stop",
  "world.jump",
  "world.climb",
  "world.swim",
  "world.crawl",
  "world.fly",
  "world.mount",
  "world.dismount",
  "world.travel",
  "world.follow_route",
  "world.navigate",
  "world.scout",
  "world.guard",
  "world.observe",
  "world.search",
  "world.study",
  "world.investigate",
  "world.listen",
  "world.hide",
  "world.interact",
  "world.utilize",
  "world.use_tool",
  "world.pickup",
  "world.drop",
  "world.transfer_item",
  "world.equip",
  "world.unequip",
  "world.attune",
  "world.unattune",
  "world.use_item",
  "world.cast_spell",
  "world.use_ability",
  "world.help",
  "world.influence",
  "world.speak",
  "world.ask_question",
  "world.answer",
  "world.whisper",
  "world.ask_human",
  "world.rest_short",
  "world.rest_long",
  "world.take_watch",
  "world.wait",
  "world.decline",
  "world.stop_activity",
  "world.attempt_task"
] as const;

export type WorldAffordanceType = (typeof WORLD_AFFORDANCE_TYPES)[number];


export const FIRST_SLICE_WORLD_TYPES: readonly WorldAffordanceType[] = [
  "world.follow",
  "world.move",
  "world.interact",
  "world.speak",
  "world.wait"
];
